const employeesActionTypes = {
  FETCH_EMPLOYEES: "FETCH_EMPLOYEES",
  FETCH_EMPLOYEES_SUCCESS: "FETCH_EMPLOYEES_SUCCESS",
  FETCH_EMPLOYEES_FAIL: "FETCH_EMPLOYEES_FAIL",

  UPDATE_EMPLOYEE_STATUS: "UPDATE_EMPLOYEE_STATUS",
  UPDATE_EMPLOYEE_STATUS_SUCCESS: "UPDATE_EMPLOYEE_STATUS_SUCCESS",
  UPDATE_EMPLOYEE_STATUS_FAIL: "UPDATE_EMPLOYEE_STATUS_FAIL",
};

export default employeesActionTypes;
