const employeesActionTypes = {
  FETCH_EMPLOYEES: 'FETCH_EMPLOYEES',
  FETCH_EMPLOYEES_SUCCESS: 'FETCH_EMPLOYEES_SUCCESS',
  FETCH_EMPLOYEES_FAIL: 'FETCH_EMPLOYEES_FAIL',

};

export default employeesActionTypes;
